---
language: node_js
node_js:
  - 4
  - stable
dist: precise
cache:
  yarn: true
  directories:
  - node_modules
env:
  - NODE_ENV=development
  - NODE_ENV=production
matrix:
  fast_finish: true
install:
  - NODE_ENV=development yarn install
before_script:
  - yarn toc && git diff --exit-code README.md
  - if [ "${NODE_ENV}" = "production" ]; then yarn build; fi
script:
  - yarn lint
<<<<<<< HEAD
  - AST_COMPARE=1 yarn test || AST_COMPARE yarn test -- --runInBand
=======
  - AST_COMPARE=1 yarn test -- --runInBand
  - if [ "${NODE_ENV}" = "development" ]; then yarn codecov; fi
deploy:
  provider: script
  script: website/deploy.sh
  skip_cleanup: true
  on:
    branch: master
    node: stable
>>>>>>> refs/remotes/prettier/master
